### ISSUE TITLE
feat: better GitHub guide

### ISSUE THREAD

**Issue by BereketEngida** [Bekacru/getting-involved-in-open-source-test-2#1]
The current Github guide could use some more information. It would be great to have a more comprehensive guide about GitHub. Plus, I'm interested in contributing, but I couldn't find any contribution guide, having a contribution guide would be awesome

**Comment by Bekacru** [comment]
Hey thanks for the suggestion. You're right there should be more information there. I'll definitely add the contribution guide asap so if you like to help you can :)
